package com.shortcuts.app.service

import com.shortcuts.app.data.Action
import com.shortcuts.app.data.ActionType
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow

/** Durable representation of a recording that has not yet been saved or discarded. */
data class PersistedRecorderSession(
    val isRecording: Boolean,
    val recordedActions: List<Action>
)

/**
 * Storage boundary for an in-progress recording. Keeping this free of Android APIs makes the
 * recorder's ownership and persistence behavior unit-testable.
 */
interface RecorderSessionStore {
    fun read(): PersistedRecorderSession?
    fun write(session: PersistedRecorderSession)
    fun clear()
}

class InMemoryRecorderSessionStore : RecorderSessionStore {
    private var session: PersistedRecorderSession? = null

    override fun read(): PersistedRecorderSession? = session

    override fun write(session: PersistedRecorderSession) {
        this.session = session
    }

    override fun clear() {
        session = null
    }
}

/**
 * Process-scoped recording owner. It deliberately has no composable or service lifecycle
 * dependency: a screen can disappear and be recreated without changing the session.
 */
class RecorderSessionOwner(
    initialStore: RecorderSessionStore = InMemoryRecorderSessionStore(),
    private val nowMillis: () -> Long = { System.currentTimeMillis() }
) {
    private val lock = Any()
    private var store = initialStore
    private var stopRequestedAtMillis = Long.MAX_VALUE
    private var lastSeenForegroundPackage: String? = null
    private var lastAppBeforeLauncherPackage: String? = null
    private var pendingLauncherClick: Action? = null
    private var lastClickTarget: String? = null
    private var lastClickAtMillis: Long = Long.MIN_VALUE
    private var pendingScroll: PendingScroll? = null
    private val lastScrollPositionByTarget = mutableMapOf<String, ScrollPosition>()

    private val _isRecording = MutableStateFlow(false)
    val isRecording: StateFlow<Boolean> = _isRecording.asStateFlow()

    private val _recordedActions = MutableStateFlow<List<Action>>(emptyList())
    val recordedActions: StateFlow<List<Action>> = _recordedActions.asStateFlow()

    init {
        restore()
    }

    fun replaceStore(newStore: RecorderSessionStore) = synchronized(lock) {
        store = newStore
        restoreLocked()
    }

    fun restore() = synchronized(lock) {
        restoreLocked()
    }

    fun start() = synchronized(lock) {
        stopRequestedAtMillis = Long.MAX_VALUE
        resetForegroundTrackingLocked()
        _recordedActions.value = emptyList()
        _isRecording.value = true
        persistLocked()
    }

    /**
     * Stops atomically with event processing. The timestamp guard also rejects an accessibility
     * event generated by the stop tap if Android delivers it after this request.
     */
    fun stop() = synchronized(lock) {
        flushPendingScrollLocked()
        stopRequestedAtMillis = nowMillis()
        resetForegroundTrackingLocked()
        _isRecording.value = false
        persistLocked()
    }

    fun setRecordingForTest(isRecording: Boolean) = synchronized(lock) {
        stopRequestedAtMillis = if (isRecording) Long.MAX_VALUE else nowMillis()
        resetForegroundTrackingLocked()
        _isRecording.value = isRecording
        persistLocked()
    }

    fun clear() = synchronized(lock) {
        stopRequestedAtMillis = Long.MAX_VALUE
        resetForegroundTrackingLocked()
        _isRecording.value = false
        _recordedActions.value = emptyList()
        store.clear()
    }

    fun processEvent(
        event: RecorderEvent,
        myPackageName: String,
        launcherPackage: String? = null,
        transientPackages: Set<String> = emptySet()
    ) {
        synchronized(lock) {
            if (!_isRecording.value || event.occurredAtMillis >= stopRequestedAtMillis) return

            if (event.eventType == RecorderEventType.APP_CHANGE) {
                processAppChangeLocked(event, myPackageName, launcherPackage, transientPackages)
                return
            }

            if (isIgnoredPackage(event.packageName, myPackageName, transientPackages)) return

            if (event.eventType == RecorderEventType.SCROLL) {
                processScrollLocked(event)
                return
            }

            flushPendingScrollLocked()
            if (event.eventType == RecorderEventType.CLICK && isDuplicateClickLocked(event)) return

            val action = when (event.eventType) {
                RecorderEventType.CLICK -> createClickAction(event)
                RecorderEventType.TEXT_CHANGE -> createTypeAction(event)
                RecorderEventType.SCROLL -> null
                RecorderEventType.APP_CHANGE -> null
            } ?: return

            // Keep an ordinary launcher tap unless the next app-change proves it opened an app.
            pendingLauncherClick = if (
                event.eventType == RecorderEventType.CLICK && event.packageName == launcherPackage
            ) {
                action
            } else {
                null
            }
            appendActionLocked(action)
        }
    }

    private fun processAppChangeLocked(
        event: RecorderEvent,
        myPackageName: String,
        launcherPackage: String?,
        transientPackages: Set<String>
    ) {
        if (event.packageName.isBlank()) return
        if (isIgnoredPackage(event.packageName, myPackageName, transientPackages)) return
        flushPendingScrollLocked()

        val previousPackage = lastSeenForegroundPackage
        val isLauncher = event.packageName == launcherPackage
        val pendingClick = pendingLauncherClick
        if (isLauncher) {
            if (lastSeenForegroundPackage != null && lastSeenForegroundPackage != launcherPackage) {
                lastAppBeforeLauncherPackage = lastSeenForegroundPackage
            }
            lastSeenForegroundPackage = event.packageName
            return
        }
        if (event.packageName == previousPackage) return

        val returnedToSameApp = previousPackage == launcherPackage &&
            event.packageName == lastAppBeforeLauncherPackage
        val launchedFromHome = !returnedToSameApp &&
            (previousPackage == launcherPackage || pendingClick != null)
        if (launchedFromHome) {
            discardPendingLauncherClickLocked(pendingClick)
            appendActionLocked(
                Action(
                    actionType = ActionType.APP_INTENT,
                    packageName = event.packageName,
                    delayMillis = 500L
                )
            )
        } else if (returnedToSameApp && discardPendingLauncherClickLocked(pendingClick)) {
            // Returning to the same app is not a replayable shortcut step.
            persistLocked()
        }
        pendingLauncherClick = null
        lastSeenForegroundPackage = event.packageName
        lastAppBeforeLauncherPackage = event.packageName
    }

    private fun appendActionLocked(action: Action) {
        val currentActions = _recordedActions.value
        _recordedActions.value = if (
            action.uiActionType == "TYPE_TEXT" &&
            currentActions.lastOrNull()?.uiActionType == "TYPE_TEXT" &&
            currentActions.last().targetNodeId == action.targetNodeId &&
            currentActions.last().targetText == action.targetText
        ) {
            currentActions.dropLast(1) + action
        } else {
            currentActions + action
        }
        persistLocked()
    }

    private fun restoreLocked() {
        val saved = store.read()
        stopRequestedAtMillis = if (saved?.isRecording == true) Long.MAX_VALUE else nowMillis()
        resetForegroundTrackingLocked()
        _isRecording.value = saved?.isRecording ?: false
        _recordedActions.value = saved?.recordedActions ?: emptyList()
    }

    private fun persistLocked() {
        store.write(PersistedRecorderSession(_isRecording.value, _recordedActions.value))
    }

    private fun resetForegroundTrackingLocked() {
        lastSeenForegroundPackage = null
        lastAppBeforeLauncherPackage = null
        pendingLauncherClick = null
        lastClickTarget = null
        lastClickAtMillis = Long.MIN_VALUE
        pendingScroll = null
        lastScrollPositionByTarget.clear()
    }

    private fun discardPendingLauncherClickLocked(pendingClick: Action?): Boolean {
        if (pendingClick == null || _recordedActions.value.lastOrNull() != pendingClick) return false
        _recordedActions.value = _recordedActions.value.dropLast(1)
        return true
    }

    private fun createClickAction(event: RecorderEvent): Action? {
        val targetText = event.sourceText ?: event.sourceContentDescription
        val targetNodeId = event.sourceViewId
        if (targetText.isNullOrBlank() && targetNodeId.isNullOrBlank() && event.screenX == null) return null

        return Action(
            actionType = ActionType.UI_AUTOMATION,
            uiActionType = "TAP",
            targetText = targetText,
            targetNodeId = targetNodeId,
            targetContentDescription = event.sourceContentDescription,
            targetClassName = event.sourceClassName,
            screenX = event.screenX,
            screenY = event.screenY,
            delayMillis = 500L
        )
    }

    private fun createTypeAction(event: RecorderEvent): Action {
        return Action(
            actionType = ActionType.UI_AUTOMATION,
            uiActionType = "TYPE_TEXT",
            targetText = event.sourceText ?: event.sourceContentDescription,
            targetNodeId = event.sourceViewId,
            targetContentDescription = event.sourceContentDescription,
            targetClassName = event.sourceClassName,
            textInput = event.enteredText,
            delayMillis = 500L
        )
    }

    /** Commits the last raw scroll only after its burst has gone quiet. */
    fun flushPendingScroll() = synchronized(lock) {
        if (_isRecording.value) flushPendingScrollLocked()
    }

    private fun flushPendingScrollLocked() {
        val scroll = pendingScroll ?: return
        pendingScroll = null
        appendActionLocked(createScrollAction(scroll.event, scroll.direction))
    }

    private fun processScrollLocked(event: RecorderEvent) {
        val targetKey = scrollTargetKey(event)
        val timestamp = eventTimestamp(event)
        val previousScroll = pendingScroll
        if (previousScroll != null &&
            (previousScroll.targetKey != targetKey || timestamp - previousScroll.lastEventAtMillis >= SCROLL_QUIET_PERIOD_MS)
        ) {
            flushPendingScrollLocked()
        }

        val previousPosition = lastScrollPositionByTarget[targetKey]
        val direction = scrollDirection(event, previousPosition)
        val currentPosition = ScrollPosition(event.scrollX, event.scrollY)
        if (currentPosition.hasValue) lastScrollPositionByTarget[targetKey] = currentPosition

        pendingScroll = PendingScroll(
            event = event,
            targetKey = targetKey,
            lastEventAtMillis = timestamp,
            direction = direction ?: pendingScroll?.takeIf { it.targetKey == targetKey }?.direction ?: "FORWARD"
        )
    }

    private fun isDuplicateClickLocked(event: RecorderEvent): Boolean {
        val target = clickTargetKey(event)
        val timestamp = eventTimestamp(event)
        val duplicate = target == lastClickTarget && timestamp - lastClickAtMillis in 0 until CLICK_DEBOUNCE_MS
        lastClickTarget = target
        lastClickAtMillis = timestamp
        return duplicate
    }

    private fun isIgnoredPackage(
        packageName: String,
        myPackageName: String,
        transientPackages: Set<String>
    ): Boolean = packageName == myPackageName ||
        packageName == SYSTEM_UI_PACKAGE ||
        packageName in KNOWN_TRANSIENT_PACKAGES ||
        packageName in transientPackages

    private fun createScrollAction(event: RecorderEvent, direction: String): Action = Action(
        actionType = ActionType.UI_AUTOMATION,
        uiActionType = "SCROLL",
        scrollDirection = direction,
        targetText = event.sourceText ?: event.sourceContentDescription,
        targetNodeId = event.sourceViewId,
        targetContentDescription = event.sourceContentDescription,
        targetClassName = event.sourceClassName,
        delayMillis = 700L
    )

    private fun eventTimestamp(event: RecorderEvent): Long =
        event.occurredAtMillis.takeUnless { it == Long.MIN_VALUE } ?: nowMillis()

    private companion object {
        const val SYSTEM_UI_PACKAGE = "com.android.systemui"
        const val CLICK_DEBOUNCE_MS = 350L
        const val SCROLL_QUIET_PERIOD_MS = 250L
        val KNOWN_TRANSIENT_PACKAGES = setOf(
            "android",
            "com.android.permissioncontroller",
            "com.google.android.permissioncontroller",
            "com.samsung.android.permissioncontroller",
            "com.android.packageinstaller",
            "com.google.android.packageinstaller",
            "com.android.intentresolver",
            "com.google.android.gms"
        )

        fun clickTargetKey(event: RecorderEvent): String = listOf(
            event.packageName,
            event.sourceViewId.orEmpty(),
            event.sourceText ?: event.sourceContentDescription.orEmpty(),
            event.sourceClassName.orEmpty(),
            event.screenX?.toString().orEmpty(),
            event.screenY?.toString().orEmpty()
        ).joinToString("|")

        fun scrollTargetKey(event: RecorderEvent): String = listOf(
            event.packageName,
            event.sourceViewId.orEmpty(),
            event.sourceClassName.orEmpty(),
            event.screenX?.toString().orEmpty(),
            event.screenY?.toString().orEmpty()
        ).joinToString("|")

        fun scrollDirection(event: RecorderEvent, previous: ScrollPosition?): String? {
            val verticalDelta = event.scrollDeltaY ?: difference(event.scrollY, previous?.y)
            val horizontalDelta = event.scrollDeltaX ?: difference(event.scrollX, previous?.x)
            val dominantDelta = when {
                verticalDelta != null && horizontalDelta != null &&
                    kotlin.math.abs(verticalDelta) >= kotlin.math.abs(horizontalDelta) -> verticalDelta
                horizontalDelta != null -> horizontalDelta
                else -> verticalDelta
            }
            if (dominantDelta != null && dominantDelta != 0) {
                return if (dominantDelta > 0) "FORWARD" else "BACKWARD"
            }

            val indexDelta = difference(event.toIndex, event.fromIndex)
            return when {
                indexDelta == null || indexDelta == 0 -> null
                indexDelta > 0 -> "FORWARD"
                else -> "BACKWARD"
            }
        }

        fun difference(current: Int?, previous: Int?): Int? =
            if (current == null || previous == null) null else current - previous
    }

    private data class PendingScroll(
        val event: RecorderEvent,
        val targetKey: String,
        val lastEventAtMillis: Long,
        val direction: String
    )

    private data class ScrollPosition(val x: Int?, val y: Int?) {
        val hasValue: Boolean get() = x != null || y != null
    }
}
