package com.shortcuts.app.service

import com.shortcuts.app.data.Action
import com.shortcuts.app.data.ActionType
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow

/** Durable representation of a recording that has not yet been saved or discarded. */
data class PersistedRecorderSession(
    val isRecording: Boolean,
    val recordedActions: List<Action>
)

/**
 * Storage boundary for an in-progress recording. Keeping this free of Android APIs makes the
 * recorder's ownership and persistence behavior unit-testable.
 */
interface RecorderSessionStore {
    fun read(): PersistedRecorderSession?
    fun write(session: PersistedRecorderSession)
    fun clear()
}

class InMemoryRecorderSessionStore : RecorderSessionStore {
    private var session: PersistedRecorderSession? = null

    override fun read(): PersistedRecorderSession? = session

    override fun write(session: PersistedRecorderSession) {
        this.session = session
    }

    override fun clear() {
        session = null
    }
}

/**
 * Process-scoped recording owner. It deliberately has no composable or service lifecycle
 * dependency: a screen can disappear and be recreated without changing the session.
 */
class RecorderSessionOwner(
    initialStore: RecorderSessionStore = InMemoryRecorderSessionStore(),
    private val nowMillis: () -> Long = { System.currentTimeMillis() }
) {
    private val lock = Any()
    private var store = initialStore
    private var stopRequestedAtMillis = Long.MAX_VALUE
    private var lastSeenForegroundPackage: String? = null
    private var lastAppBeforeLauncherPackage: String? = null
    private val pendingLauncherClicks = mutableListOf<Action>()
    private var lastClickTarget: String? = null
    private var lastClickAtMillis: Long = Long.MIN_VALUE
    private var pendingText: PendingText? = null
    private var lastCommittedText: PendingText? = null
    private var focusedField: RecorderEvent? = null
    private var pendingScroll: PendingScroll? = null
    private val lastScrollPositionByTarget = mutableMapOf<String, ScrollPosition>()

    private val _isRecording = MutableStateFlow(false)
    val isRecording: StateFlow<Boolean> = _isRecording.asStateFlow()

    private val _recordedActions = MutableStateFlow<List<Action>>(emptyList())
    val recordedActions: StateFlow<List<Action>> = _recordedActions.asStateFlow()

    init {
        restore()
    }

    fun replaceStore(newStore: RecorderSessionStore) = synchronized(lock) {
        store = newStore
        restoreLocked()
    }

    fun restore() = synchronized(lock) {
        restoreLocked()
    }

    fun start() = synchronized(lock) {
        stopRequestedAtMillis = Long.MAX_VALUE
        resetForegroundTrackingLocked()
        _recordedActions.value = emptyList()
        _isRecording.value = true
        persistLocked()
    }

    /**
     * Stops atomically with event processing. The timestamp guard also rejects an accessibility
     * event generated by the stop tap if Android delivers it after this request.
     */
    fun stop() = synchronized(lock) {
        flushPendingTextLocked()
        flushPendingScrollLocked()
        stopRequestedAtMillis = nowMillis()
        resetForegroundTrackingLocked()
        _isRecording.value = false
        persistLocked()
    }

    fun setRecordingForTest(isRecording: Boolean) = synchronized(lock) {
        stopRequestedAtMillis = if (isRecording) Long.MAX_VALUE else nowMillis()
        resetForegroundTrackingLocked()
        _isRecording.value = isRecording
        persistLocked()
    }

    fun clear() = synchronized(lock) {
        stopRequestedAtMillis = Long.MAX_VALUE
        resetForegroundTrackingLocked()
        _isRecording.value = false
        _recordedActions.value = emptyList()
        store.clear()
    }

    fun processEvent(
        event: RecorderEvent,
        myPackageName: String,
        launcherPackage: String? = null,
        transientPackages: Set<String> = emptySet()
    ) {
        synchronized(lock) {
            if (!_isRecording.value || event.occurredAtMillis >= stopRequestedAtMillis) return

            val isIgnored = event.packageName.isBlank() || isIgnoredPackage(event.packageName, myPackageName, transientPackages)
            val previousPackage = lastSeenForegroundPackage
            val isPackageTransition = !isIgnored && event.packageName != previousPackage

            if (isPackageTransition) {
                processForegroundTransitionLocked(event.packageName, launcherPackage)
            }

            if (event.eventType == RecorderEventType.APP_CHANGE) {
                if (!isIgnored && !isPackageTransition) {
                    inferSubmitFromWindowChangeLocked(event)
                }
                return
            }

            if (event.eventType == RecorderEventType.SELECTION_CHANGE) return

            if (event.eventType == RecorderEventType.PRESS_ENTER) {
                processPressEnterLocked(event)
                return
            }

            if (isIgnored) return

            when (event.eventType) {
                RecorderEventType.TEXT_CHANGE -> {
                    processTextChangeLocked(event)
                    return
                }
                RecorderEventType.FOCUS -> {
                    processFocusChangeLocked(event)
                    return
                }
                RecorderEventType.CONTENT_CHANGE -> {
                    processContentChangeLocked(event)
                    return
                }
                else -> Unit
            }

            when (event.eventType) {
                RecorderEventType.TEXT_CHANGE -> {
                    processTextChangeLocked(event)
                    return
                }
                RecorderEventType.FOCUS -> {
                    processFocusChangeLocked(event)
                    return
                }
                RecorderEventType.CONTENT_CHANGE -> {
                    processContentChangeLocked(event)
                    return
                }
                else -> Unit
            }

            if (event.eventType == RecorderEventType.SCROLL) {
                if (shouldSuppressEditingScrollLocked(event)) return
                flushPendingTextLocked()
                // A real scroll closes submit inference, but the editable field may remain focused
                // and must stay eligible for a later live-text fallback read.
                lastCommittedText = null
                processScrollLocked(event)
                return
            }

            flushPendingTextLocked()
            flushPendingScrollLocked()
            if (
                event.eventType in setOf(RecorderEventType.CLICK, RecorderEventType.LONG_PRESS) &&
                isDuplicateClickLocked(event)
            ) return

            clearTextCommitCandidateLocked()

            val action = when (event.eventType) {
                RecorderEventType.CLICK -> createClickAction(event)
                RecorderEventType.LONG_PRESS -> createLongPressAction(event)
                RecorderEventType.TEXT_CHANGE,
                RecorderEventType.SELECTION_CHANGE,
                RecorderEventType.FOCUS,
                RecorderEventType.CONTENT_CHANGE,
                RecorderEventType.PRESS_ENTER -> null
                RecorderEventType.SCROLL -> null
                RecorderEventType.APP_CHANGE -> null
            } ?: return

            // Launcher clicks are speculative until a following app-change proves they launched
            // an app. Keep the whole burst: Android can report both a Home surface click and the
            // icon click, and tracking only the latest one left the earlier bogus tap behind.
            if (event.eventType == RecorderEventType.CLICK && event.packageName == launcherPackage) {
                pendingLauncherClicks += action
            } else {
                pendingLauncherClicks.clear()
            }
            appendActionLocked(action)
            if (event.eventType == RecorderEventType.CLICK) {
                focusedField = event.takeIf { it.sourceIsEditable }
            } else if (event.eventType == RecorderEventType.LONG_PRESS) {
                focusedField = null
            }
        }
    }

    /**
     * Returns the editable field whose focus was observed through a focus or click callback.
     * The Android boundary uses this solely as a gate: it performs no node-tree lookup when null.
     */
    fun trackedFocusedEditableField(): RecorderEvent? = synchronized(lock) {
        focusedField.takeIf { _isRecording.value }
    }

    /**
     * Feeds a live `findFocus(FOCUS_INPUT)` snapshot into the same text-change buffer used by
     * normal TYPE_VIEW_TEXT_CHANGED callbacks. Returns true only when the value really changed.
     */
    fun processLiveFocusedTextSnapshot(event: RecorderEvent): Boolean = synchronized(lock) {
        if (!_isRecording.value || event.occurredAtMillis >= stopRequestedAtMillis) return false
        val tracked = focusedField ?: return false
        if (!sameTextTarget(tracked, event) || tracked.enteredText == event.enteredText) return false

        processTextChangeLocked(event.copy(eventType = RecorderEventType.TEXT_CHANGE))
        true
    }

    /**
     * Appends a pre-built [Action] from the manual "mark a tap" helper overlay.
     *
     * This is the entry point for [TapMarkOverlay]-sourced steps. It uses the same
     * [appendActionLocked] path as [processEvent], so the resulting step appears
     * identically in the review screen and persisted recording.
     */
    fun appendManualAction(action: Action) = synchronized(lock) {
        if (!_isRecording.value) return
        flushPendingTextLocked()
        flushPendingScrollLocked()
        clearTextCommitCandidateLocked()
        focusedField = null
        pendingLauncherClicks.clear()
        appendActionLocked(action)
    }

    private fun processForegroundTransitionLocked(
        newPackageName: String,
        launcherPackage: String?
    ) {
        flushPendingTextLocked()
        clearTextCommitCandidateLocked()
        focusedField = null
        flushPendingScrollLocked()

        val previousPackage = lastSeenForegroundPackage
        val isLauncher = newPackageName == launcherPackage
        val hasPendingLauncherClicks = pendingLauncherClicks.isNotEmpty()

        if (isLauncher) {
            if (previousPackage != null && previousPackage != launcherPackage) {
                lastAppBeforeLauncherPackage = previousPackage
            }
            lastSeenForegroundPackage = newPackageName
            return
        }

        // previousPackage == null means "no baseline established yet" (the very first
        // foreground-touching event this session), which must never be treated as "we were
        // on the launcher" just because launcherPackage also happens to be unset/null in a
        // test harness — both being null is not evidence of anything.
        val wasOnLauncher = previousPackage != null && previousPackage == launcherPackage
        val returnedToSameApp = wasOnLauncher && newPackageName == lastAppBeforeLauncherPackage
        val launchedFromHome = !returnedToSameApp && (wasOnLauncher || hasPendingLauncherClicks)
            
        if (launchedFromHome) {
            discardPendingLauncherClicksLocked()
            appendActionLocked(
                Action(
                    actionType = ActionType.APP_INTENT,
                    packageName = newPackageName,
                    delayMillis = 500L
                )
            )
        } else if (returnedToSameApp && discardPendingLauncherClicksLocked()) {
            // Returning to the same app is not a replayable shortcut step.
            persistLocked()
        }
        pendingLauncherClicks.clear()
        lastSeenForegroundPackage = newPackageName
        lastAppBeforeLauncherPackage = newPackageName
    }

    private fun appendActionLocked(action: Action) {
        val currentActions = _recordedActions.value
        _recordedActions.value = if (
            action.uiActionType == "TYPE_TEXT" &&
            currentActions.lastOrNull()?.uiActionType == "TYPE_TEXT" &&
            currentActions.last().targetNodeId == action.targetNodeId &&
            currentActions.last().targetPackageName == action.targetPackageName &&
            currentActions.last().targetClassName == action.targetClassName
        ) {
            currentActions.dropLast(1) + action
        } else {
            currentActions + action
        }
        persistLocked()
    }

    private fun restoreLocked() {
        val saved = store.read()
        stopRequestedAtMillis = if (saved?.isRecording == true) Long.MAX_VALUE else nowMillis()
        resetForegroundTrackingLocked()
        _isRecording.value = saved?.isRecording ?: false
        _recordedActions.value = saved?.recordedActions ?: emptyList()
    }

    private fun persistLocked() {
        store.write(PersistedRecorderSession(_isRecording.value, _recordedActions.value))
    }

    private fun resetForegroundTrackingLocked() {
        lastSeenForegroundPackage = null
        lastAppBeforeLauncherPackage = null
        pendingLauncherClicks.clear()
        lastClickTarget = null
        lastClickAtMillis = Long.MIN_VALUE
        pendingText = null
        lastCommittedText = null
        focusedField = null
        pendingScroll = null
        lastScrollPositionByTarget.clear()
    }

    private fun discardPendingLauncherClicksLocked(): Boolean {
        if (pendingLauncherClicks.isEmpty()) return false
        val currentActions = _recordedActions.value
        if (currentActions.size < pendingLauncherClicks.size ||
            currentActions.takeLast(pendingLauncherClicks.size) != pendingLauncherClicks
        ) return false
        _recordedActions.value = currentActions.dropLast(pendingLauncherClicks.size)
        pendingLauncherClicks.clear()
        return true
    }

    private fun createClickAction(event: RecorderEvent): Action? {
        val targetText = event.sourceText ?: event.sourceContentDescription
        val targetNodeId = event.sourceViewId
        if (targetText.isNullOrBlank() && targetNodeId.isNullOrBlank() && event.screenX == null) return null

        return Action(
            actionType = ActionType.UI_AUTOMATION,
            uiActionType = "TAP",
            targetText = targetText,
            targetNodeId = targetNodeId,
            targetContentDescription = event.sourceContentDescription,
            targetClassName = event.sourceClassName,
            targetPackageName = event.packageName,
            screenX = event.screenX,
            screenY = event.screenY,
            recordedDisplayWidth = event.displaySnapshot?.width,
            recordedDisplayHeight = event.displaySnapshot?.height,
            recordedDisplayRotation = event.displaySnapshot?.rotation,
            recordedDensityDpi = event.displaySnapshot?.densityDpi,
            delayMillis = 500L
        )
    }

    private fun createLongPressAction(event: RecorderEvent): Action? =
        createClickAction(event)?.copy(uiActionType = "LONG_PRESS")

    private fun createTypeAction(event: RecorderEvent): Action {
        // A text-change node's visible text is usually the live value being edited, not a stable
        // selector. Never require that changing value to identify the field during replay.
        val stableTargetText = event.sourceText
            ?.takeUnless { it == event.enteredText }
            ?: event.sourceContentDescription
        return Action(
            actionType = ActionType.UI_AUTOMATION,
            uiActionType = "TYPE_TEXT",
            targetText = stableTargetText,
            targetNodeId = event.sourceViewId,
            targetContentDescription = event.sourceContentDescription,
            targetClassName = event.sourceClassName,
            targetPackageName = event.packageName,
            textInput = event.enteredText,
            delayMillis = 500L
        )
    }

    private fun createPressEnterAction(textAction: Action): Action = Action(
        actionType = ActionType.UI_AUTOMATION,
        uiActionType = "PRESS_ENTER",
        targetText = textAction.targetText,
        targetNodeId = textAction.targetNodeId,
        targetContentDescription = textAction.targetContentDescription,
        targetClassName = textAction.targetClassName,
        targetPackageName = textAction.targetPackageName,
        delayMillis = 500L
    )

    private fun processTextChangeLocked(event: RecorderEvent) {
        pendingLauncherClicks.clear()
        flushPendingScrollLocked()

        val targetKey = textTargetKey(event)
        val timestamp = eventTimestamp(event)
        val previous = pendingText
        if (previous != null &&
            (previous.targetKey != targetKey || timestamp - previous.lastEventAtMillis >= TEXT_QUIET_PERIOD_MS)
        ) {
            flushPendingTextLocked()
        }

        pendingText = PendingText(event, targetKey, timestamp)
        focusedField = event
    }

    private fun processFocusChangeLocked(event: RecorderEvent) {
        val targetKey = textTargetKey(event)
        val pending = pendingText
        if (pending != null && pending.targetKey != targetKey) {
            flushPendingTextLocked()
        }
        if (lastCommittedText?.targetKey != targetKey) clearTextCommitCandidateLocked()
        focusedField = event.takeIf { it.sourceIsEditable }
    }

    private fun processContentChangeLocked(event: RecorderEvent) {
        val candidate = pendingText ?: lastCommittedText ?: return
        if (candidate.event.packageName != event.packageName) return
        if (eventTimestamp(event) - candidate.lastEventAtMillis < TEXT_QUIET_PERIOD_MS) return
        commitTextAndSubmitLocked()
    }

    private fun inferSubmitFromWindowChangeLocked(event: RecorderEvent) {
        val candidate = pendingText ?: lastCommittedText ?: return
        if (candidate.event.packageName != event.packageName) return
        commitTextAndSubmitLocked()
    }

    private fun processPressEnterLocked(event: RecorderEvent) {
        flushPendingTextLocked()
        val textAction = lastCommittedText?.let { createTypeAction(it.event) }
            ?: focusedField?.let(::createTypeAction)
            ?: event.takeIf { hasTargetSelector(it) }?.let(::createTypeAction)
            ?: return
        appendActionLocked(createPressEnterAction(textAction))
        clearTextCommitCandidateLocked()
    }

    private fun commitTextAndSubmitLocked() {
        flushPendingTextLocked()
        val textAction = lastCommittedText?.let { createTypeAction(it.event) } ?: return
        appendActionLocked(createPressEnterAction(textAction))
        clearTextCommitCandidateLocked()
    }

    /** Commits the final full value from a field-edit burst as one durable step. */
    fun flushPendingText() = synchronized(lock) {
        if (_isRecording.value) flushPendingTextLocked()
    }

    private fun flushPendingTextLocked() {
        val text = pendingText ?: return
        pendingText = null
        appendActionLocked(createTypeAction(text.event))
        lastCommittedText = text
    }

    private fun clearTextCommitCandidateLocked() {
        lastCommittedText = null
        
    }

    /** Commits the last raw scroll only after its burst has gone quiet. */
    fun flushPendingScroll() = synchronized(lock) {
        if (_isRecording.value) flushPendingScrollLocked()
    }

    private fun flushPendingScrollLocked() {
        val scroll = pendingScroll ?: return
        pendingScroll = null
        appendActionLocked(createScrollAction(scroll.event, scroll.direction))
    }

    private fun processScrollLocked(event: RecorderEvent) {
        val targetKey = scrollTargetKey(event)
        val timestamp = eventTimestamp(event)
        val previousScroll = pendingScroll
        if (previousScroll != null &&
            (previousScroll.targetKey != targetKey || timestamp - previousScroll.lastEventAtMillis >= SCROLL_QUIET_PERIOD_MS)
        ) {
            flushPendingScrollLocked()
        }

        val previousPosition = lastScrollPositionByTarget[targetKey]
        val direction = scrollDirection(event, previousPosition)
        val currentPosition = ScrollPosition(event.scrollX, event.scrollY)
        if (currentPosition.hasValue) lastScrollPositionByTarget[targetKey] = currentPosition

        pendingScroll = PendingScroll(
            event = event,
            targetKey = targetKey,
            lastEventAtMillis = timestamp,
            direction = direction ?: pendingScroll?.takeIf { it.targetKey == targetKey }?.direction ?: "FORWARD"
        )
    }

    private fun shouldSuppressEditingScrollLocked(event: RecorderEvent): Boolean {
        val field = focusedField ?: return false
        return textTargetKey(field) != textTargetKey(event) && sameWindow(field, event)
    }

    private fun isDuplicateClickLocked(event: RecorderEvent): Boolean {
        val target = clickTargetKey(event)
        val timestamp = eventTimestamp(event)
        val duplicate = target == lastClickTarget && timestamp - lastClickAtMillis in 0 until CLICK_DEBOUNCE_MS
        if (!duplicate) {
            lastClickTarget = target
            lastClickAtMillis = timestamp
        }
        return duplicate
    }

    private fun isIgnoredPackage(
        packageName: String,
        myPackageName: String,
        transientPackages: Set<String>
    ): Boolean = packageName == myPackageName ||
        packageName == SYSTEM_UI_PACKAGE ||
        packageName in KNOWN_TRANSIENT_PACKAGES ||
        packageName in transientPackages

    private fun createScrollAction(event: RecorderEvent, direction: String): Action = Action(
        actionType = ActionType.UI_AUTOMATION,
        uiActionType = "SCROLL",
        scrollDirection = direction,
        targetText = event.sourceText ?: event.sourceContentDescription,
        targetNodeId = event.sourceViewId,
        targetContentDescription = event.sourceContentDescription,
        targetClassName = event.sourceClassName,
        targetPackageName = event.packageName,
        delayMillis = 700L
    )

    private fun eventTimestamp(event: RecorderEvent): Long =
        event.occurredAtMillis.takeUnless { it == Long.MIN_VALUE } ?: nowMillis()

    private companion object {
        const val SYSTEM_UI_PACKAGE = "com.android.systemui"
        const val CLICK_DEBOUNCE_MS = 350L
        const val SCROLL_QUIET_PERIOD_MS = 250L
        const val TEXT_QUIET_PERIOD_MS = 400L
        val KNOWN_TRANSIENT_PACKAGES = setOf(
            "android",
            "com.android.permissioncontroller",
            "com.google.android.permissioncontroller",
            "com.samsung.android.permissioncontroller",
            "com.android.packageinstaller",
            "com.google.android.packageinstaller",
            "com.android.intentresolver",
            "com.google.android.gms"
        )

        fun clickTargetKey(event: RecorderEvent): String = listOf(
            event.packageName,
            event.sourceViewId.orEmpty(),
            event.sourceText ?: event.sourceContentDescription.orEmpty(),
            event.sourceClassName.orEmpty(),
            event.screenX?.toString().orEmpty(),
            event.screenY?.toString().orEmpty()
        ).joinToString("|")

        fun scrollTargetKey(event: RecorderEvent): String = listOf(
            event.packageName,
            event.sourceViewId.orEmpty(),
            event.sourceClassName.orEmpty(),
            event.screenX?.toString().orEmpty(),
            event.screenY?.toString().orEmpty()
        ).joinToString("|")

        fun textTargetKey(event: RecorderEvent): String = listOf(
            event.packageName,
            event.sourceViewId.orEmpty(),
            event.sourceClassName.orEmpty()
        ).joinToString("|")

        fun sameTextTarget(first: RecorderEvent, second: RecorderEvent): Boolean =
            textTargetKey(first) == textTargetKey(second) && sameWindow(first, second)

        fun sameWindow(first: RecorderEvent, second: RecorderEvent): Boolean =
            first.packageName == second.packageName &&
                (first.windowId == null || second.windowId == null || first.windowId == second.windowId)

        fun hasTargetSelector(event: RecorderEvent): Boolean =
            event.sourceViewId != null || event.sourceText != null ||
                event.sourceContentDescription != null || event.sourceClassName != null

        fun scrollDirection(event: RecorderEvent, previous: ScrollPosition?): String? {
            val verticalDelta = event.scrollDeltaY ?: difference(event.scrollY, previous?.y)
            val horizontalDelta = event.scrollDeltaX ?: difference(event.scrollX, previous?.x)
            val dominantDelta = when {
                verticalDelta != null && horizontalDelta != null &&
                    kotlin.math.abs(verticalDelta) >= kotlin.math.abs(horizontalDelta) -> verticalDelta
                horizontalDelta != null -> horizontalDelta
                else -> verticalDelta
            }
            if (dominantDelta != null && dominantDelta != 0) {
                return if (dominantDelta > 0) "FORWARD" else "BACKWARD"
            }

            val indexDelta = difference(event.toIndex, event.fromIndex)
            return when {
                indexDelta == null || indexDelta == 0 -> null
                indexDelta > 0 -> "FORWARD"
                else -> "BACKWARD"
            }
        }

        fun difference(current: Int?, previous: Int?): Int? =
            if (current == null || previous == null) null else current - previous
    }

    private data class PendingScroll(
        val event: RecorderEvent,
        val targetKey: String,
        val lastEventAtMillis: Long,
        val direction: String
    )

    private data class PendingText(
        val event: RecorderEvent,
        val targetKey: String,
        val lastEventAtMillis: Long
    )

    private data class ScrollPosition(val x: Int?, val y: Int?) {
        val hasValue: Boolean get() = x != null || y != null
    }
}
