package com.shortcuts.app.service

import com.shortcuts.app.data.Action
import com.shortcuts.app.data.ActionType
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow

/** Durable representation of a recording that has not yet been saved or discarded. */
data class PersistedRecorderSession(
    val isRecording: Boolean,
    val recordedActions: List<Action>
)

/**
 * Storage boundary for an in-progress recording. Keeping this free of Android APIs makes the
 * recorder's ownership and persistence behavior unit-testable.
 */
interface RecorderSessionStore {
    fun read(): PersistedRecorderSession?
    fun write(session: PersistedRecorderSession)
    fun clear()
}

class InMemoryRecorderSessionStore : RecorderSessionStore {
    private var session: PersistedRecorderSession? = null

    override fun read(): PersistedRecorderSession? = session

    override fun write(session: PersistedRecorderSession) {
        this.session = session
    }

    override fun clear() {
        session = null
    }
}

/**
 * Process-scoped recording owner. It deliberately has no composable or service lifecycle
 * dependency: a screen can disappear and be recreated without changing the session.
 */
class RecorderSessionOwner(
    initialStore: RecorderSessionStore = InMemoryRecorderSessionStore(),
    private val nowMillis: () -> Long = { System.currentTimeMillis() }
) {
    private val lock = Any()
    private var store = initialStore
    private var stopRequestedAtMillis = Long.MAX_VALUE
    private var lastSeenForegroundPackage: String? = null
    private var lastAppBeforeLauncherPackage: String? = null
    private var pendingLauncherClick: Action? = null

    private val _isRecording = MutableStateFlow(false)
    val isRecording: StateFlow<Boolean> = _isRecording.asStateFlow()

    private val _recordedActions = MutableStateFlow<List<Action>>(emptyList())
    val recordedActions: StateFlow<List<Action>> = _recordedActions.asStateFlow()

    init {
        restore()
    }

    fun replaceStore(newStore: RecorderSessionStore) = synchronized(lock) {
        store = newStore
        restoreLocked()
    }

    fun restore() = synchronized(lock) {
        restoreLocked()
    }

    fun start() = synchronized(lock) {
        stopRequestedAtMillis = Long.MAX_VALUE
        resetForegroundTrackingLocked()
        _recordedActions.value = emptyList()
        _isRecording.value = true
        persistLocked()
    }

    /**
     * Stops atomically with event processing. The timestamp guard also rejects an accessibility
     * event generated by the stop tap if Android delivers it after this request.
     */
    fun stop() = synchronized(lock) {
        stopRequestedAtMillis = nowMillis()
        resetForegroundTrackingLocked()
        _isRecording.value = false
        persistLocked()
    }

    fun setRecordingForTest(isRecording: Boolean) = synchronized(lock) {
        stopRequestedAtMillis = if (isRecording) Long.MAX_VALUE else nowMillis()
        resetForegroundTrackingLocked()
        _isRecording.value = isRecording
        persistLocked()
    }

    fun clear() = synchronized(lock) {
        stopRequestedAtMillis = Long.MAX_VALUE
        resetForegroundTrackingLocked()
        _isRecording.value = false
        _recordedActions.value = emptyList()
        store.clear()
    }

    fun processEvent(
        event: RecorderEvent,
        myPackageName: String,
        launcherPackage: String? = null
    ) {
        synchronized(lock) {
            if (!_isRecording.value || event.occurredAtMillis >= stopRequestedAtMillis) return

            if (event.eventType == RecorderEventType.APP_CHANGE) {
                processAppChangeLocked(event, myPackageName, launcherPackage)
                return
            }

            if (event.packageName == myPackageName || event.packageName == SYSTEM_UI_PACKAGE) return

            val action = when (event.eventType) {
                RecorderEventType.CLICK -> createClickAction(event)
                RecorderEventType.TEXT_CHANGE -> createTypeAction(event)
                RecorderEventType.SCROLL -> createScrollAction(event)
                RecorderEventType.APP_CHANGE -> null
            } ?: return

            // Keep an ordinary launcher tap unless the next app-change proves it opened an app.
            pendingLauncherClick = if (
                event.eventType == RecorderEventType.CLICK && event.packageName == launcherPackage
            ) {
                action
            } else {
                null
            }
            appendActionLocked(action)
        }
    }

    private fun processAppChangeLocked(
        event: RecorderEvent,
        myPackageName: String,
        launcherPackage: String?
    ) {
        val previousPackage = lastSeenForegroundPackage
        val isIgnoredPackage = event.packageName == myPackageName || event.packageName == SYSTEM_UI_PACKAGE
        val isLauncher = event.packageName == launcherPackage
        val pendingClick = pendingLauncherClick
        pendingLauncherClick = null

        if (event.packageName.isBlank()) return
        if (isIgnoredPackage) return
        if (isLauncher) {
            if (lastSeenForegroundPackage != null && lastSeenForegroundPackage != launcherPackage) {
                lastAppBeforeLauncherPackage = lastSeenForegroundPackage
            }
            lastSeenForegroundPackage = event.packageName
            return
        }
        if (event.packageName == previousPackage) return

        val returnedToSameApp = previousPackage == launcherPackage &&
            event.packageName == lastAppBeforeLauncherPackage
        val launchedFromHome = !returnedToSameApp &&
            (previousPackage == null || previousPackage == launcherPackage || pendingClick != null)
        if (launchedFromHome) {
            discardPendingLauncherClickLocked(pendingClick)
            appendActionLocked(
                Action(
                    actionType = ActionType.APP_INTENT,
                    packageName = event.packageName,
                    delayMillis = 500L
                )
            )
        } else if (returnedToSameApp && discardPendingLauncherClickLocked(pendingClick)) {
            // Returning to the same app is not a replayable shortcut step.
            persistLocked()
        }
        lastSeenForegroundPackage = event.packageName
        lastAppBeforeLauncherPackage = event.packageName
    }

    private fun appendActionLocked(action: Action) {
        val currentActions = _recordedActions.value
        _recordedActions.value = if (
            action.uiActionType == "TYPE_TEXT" &&
            currentActions.lastOrNull()?.uiActionType == "TYPE_TEXT" &&
            currentActions.last().targetNodeId == action.targetNodeId &&
            currentActions.last().targetText == action.targetText
        ) {
            currentActions.dropLast(1) + action
        } else {
            currentActions + action
        }
        persistLocked()
    }

    private fun restoreLocked() {
        val saved = store.read()
        stopRequestedAtMillis = if (saved?.isRecording == true) Long.MAX_VALUE else nowMillis()
        resetForegroundTrackingLocked()
        _isRecording.value = saved?.isRecording ?: false
        _recordedActions.value = saved?.recordedActions ?: emptyList()
    }

    private fun persistLocked() {
        store.write(PersistedRecorderSession(_isRecording.value, _recordedActions.value))
    }

    private fun resetForegroundTrackingLocked() {
        lastSeenForegroundPackage = null
        lastAppBeforeLauncherPackage = null
        pendingLauncherClick = null
    }

    private fun discardPendingLauncherClickLocked(pendingClick: Action?): Boolean {
        if (pendingClick == null || _recordedActions.value.lastOrNull() != pendingClick) return false
        _recordedActions.value = _recordedActions.value.dropLast(1)
        return true
    }

    private fun createClickAction(event: RecorderEvent): Action? {
        val targetText = event.sourceText ?: event.sourceContentDescription
        val targetNodeId = event.sourceViewId
        if (targetText.isNullOrBlank() && targetNodeId.isNullOrBlank() && event.screenX == null) return null

        return Action(
            actionType = ActionType.UI_AUTOMATION,
            uiActionType = "TAP",
            targetText = targetText,
            targetNodeId = targetNodeId,
            targetContentDescription = event.sourceContentDescription,
            targetClassName = event.sourceClassName,
            screenX = event.screenX,
            screenY = event.screenY,
            delayMillis = 500L
        )
    }

    private fun createTypeAction(event: RecorderEvent): Action {
        return Action(
            actionType = ActionType.UI_AUTOMATION,
            uiActionType = "TYPE_TEXT",
            targetText = event.sourceText ?: event.sourceContentDescription,
            targetNodeId = event.sourceViewId,
            targetContentDescription = event.sourceContentDescription,
            targetClassName = event.sourceClassName,
            textInput = event.enteredText,
            delayMillis = 500L
        )
    }

    private fun createScrollAction(event: RecorderEvent): Action = Action(
        actionType = ActionType.UI_AUTOMATION,
        uiActionType = "SCROLL",
        scrollDirection = "FORWARD",
        targetText = event.sourceText ?: event.sourceContentDescription,
        targetNodeId = event.sourceViewId,
        targetContentDescription = event.sourceContentDescription,
        targetClassName = event.sourceClassName,
        delayMillis = 700L
    )

    private companion object {
        const val SYSTEM_UI_PACKAGE = "com.android.systemui"
    }
}
